apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: frontendbeta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
      rel: beta
  template:
    metadata:
      labels:
        app: ui
        rel: beta
    spec:
      containers:
        - name: globomantics
          image: 493215491729.dkr.ecr.us-east-1.amazonaws.com/sample101k8s:lastest